### PR TITLE
Pre-release merge for arXiv-marXdown v0.1

### PR DESCRIPTION
**Pull request by erickpeirson**
This PR is to facilitate high-level team review prior to the first release of this app, as part of the help pages migration.

The arXiv-marXdown application builds and serves static pages from markdown sources. In order to provide portability, and to integrate with Flask's URL building and other goodies, this occurs in two steps:

1. Build: convert markdown source into Jinja2 template fragments ahead of time. Optionally, build a file-based index of the site for searching.
2. Serve: serve the site from the Jinja2 template fragments, rendering HTML on the fly.

Tips for review:
- [ ] ***Don't click on "Files changed".***
- [ ] Check out [``README.md``](https://github.com/arXiv/arxiv-markdown/blob/develop/README.md).
- [ ] Try building and running the [arXiv docs](https://github.com/arXiv/arxiv-docs) project (see below).
- [ ] If you want to dive into the code, start with the tests (perhaps in this order):
   - [building a site](https://github.com/arXiv/arxiv-markdown/blob/develop/arxiv/marxdown/tests/test_build.py)
   - [serving a site](https://github.com/arXiv/arxiv-markdown/blob/develop/arxiv/marxdown/tests/test_serve.py)
   - [how the site gets loaded from a repository](https://github.com/arXiv/arxiv-markdown/blob/develop/arxiv/marxdown/services/tests/test_source.py)
   - [building a sitemap](https://github.com/arXiv/arxiv-markdown/blob/develop/arxiv/sitemap/tests/test_build.py)

# Giving feedback
Since this is an enormous merge, the "Files changed" tab is useless.

To give feedback on code/content, browse the develop branch directly, and raise issues attached to specific lines of code.

image

Then leave a comment in this PR referencing the issue.

# Building and running the arXiv docs project 

1. Clone the arxiv-docs repo:

```bash
git clone git@github.com:arXiv/arxiv-docs.git /somewhere/docs
```

2. Install arXiv marXdown (this software).

```bash
git clone git@github.com:arXiv/arxiv-markdown.git /somewhere/arxiv-marxdown
pipenv install /somewhere/arxiv-marxdown
```

3. Build the help site.

```bash
SITE_NAME=help SOURCE_PATH=/somewhere/docs/help BUILD_PATH=/tmp/build-help pipenv run python -m arxiv.marxdown.build
```

(this might take 20-30 seconds and will spam you at the end)

4. Run the help site.

```bash
SITE_NAME=help SOURCE_PATH=/somewhere/docs/help BUILD_PATH=/tmp/build-help FLASK_APP=arxiv.marxdown.app FLASK_DEBUG=1 pipenv run flask run
```

5. Profit.

Go to http://127.0.0.1:5000. You should see:

image

### CODE REVIEW

**Comment by mhl10** [comment]
> ```shell
> git clone git@github.com:arXiv/arxiv-markdown.git /somewhere/arxiv-marxdown
> pipenv install /somewhere/arxiv-marxdown
> ```

FYI: I couldn't install the pyyaml pre-version 4.2b4 indicated in `Pipfile` unless I ran `pipenv install --pre`.

**Comment by erickpeirson** [comment]
You may also need to install ``mysqlclient``, as this dependency was omitted in `arxiv-auth`. 

```bash
pipenv install mysqlclient==1.4.1
```

**Comment by mhl10** [comment]
I initially had problems running the build; see #13.

**Comment by mhl10** [comment]
MathJax not rendering properly; see https://github.com/arXiv/arxiv-markdown/issues/14.

**Comment by mhl10** [comment]
Is 'Static' the intended breadcrumb given `SITE_NAME=help`?
screenshot 2019-02-12 10 25 25

**Comment by eawoods** [comment]
I noticed 'Static' in a build of /about also -- I think it's configurable?

**Comment by mhl10** [comment]
Double-escaping in search results (minor): see #15.

**Comment by erickpeirson** [comment]
> Is 'Static' the intended breadcrumb given `SITE_NAME=help`?
> screenshot 2019-02-12 10 25 25

> I noticed 'Static' in a build of /about also -- I think it's configurable?

Look for ``SITE_HUMAN_NAME`` and ``SITE_HUMAN_SHORT_NAME`` in the README.md

**Pull request merged**
